config/routes.rb
Rails.application.routes.draw do

 root 'accounts#index'

 resources :accounts  do
    get "update_all", on: :collection
    get "refresh", on: :member
    get "deepen", on: :member
    patch "delete_tweets", on: :member
  end

  # it looks like the only RESTful route you have for tweets is the index...
  # I'd suggest updating your routes to clearly indicate that:
  # resources :tweets, only: [:index]
 resources :tweets


end

app/models/account.rb
class Account < ActiveRecord::Base
  strip_attributes
  validates :username, presence: true, uniqueness: true
  has_many :tweets, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :account

  def self.create_with_tweets(tweets)
    tweets.each do |tweet|
      account = Account.find_by(username: tweet.user.screen_name)

      # there's a shorter way to write this using `find_or_create_by()`, which
      # is provided for all AR models.
      if Tweet.find_by(tweet_id: tweet.id)
        next
      else
        Tweet.create(account_id: account.id, text: tweet.text, tweet_id: tweet.id, created_at: tweet.created_at)
      end
    end
  end

end

app/models/twitter_client.rb
require 'twitter'

class TwitterClient
  def self.client
    Twitter::REST::Client.new do |config|
      # these values shouldn't be checked into Git! Check out a tool such as
      # figaro to help you put these in Environment Variables where they can
      # be kepts secret.
      # https://github.com/laserlemon/figaro#deployment
      config.consumer_key        = 'tUFYHKytPm9bJHEfFvc50Gzkg'
      config.consumer_secret     = 'BNQPDTzcPhAY4psGckJRt5Nd4bHxorvmIEAo7YLdB4ZUSmB9DS'
      config.access_token        = '1625578152-1wsOUgo62U2cBOaEegmAupnmxoHn9DKS74hfxkZ'
      config.access_token_secret = 'xS8pInfwVpGsyLDJnZid92bOQ3F2bxY8sJ8xpTu76lvSL'
    end
  end


  def self.get_tweets(username)
    client.user_timeline(username)
  end

  def self.get_more_tweets(username)
    client.user_timeline(username, opts ={count: 200})
  end

  def self.get_account(username)
    client.user(username)
  end

  def self.update_frontpage
    Account.all.each do |account|
      new_tweets = TwitterClient.get_tweets(account.username)
      Tweet.create_with_tweets(new_tweets)
    end
  end
end


# gets twitter_user's most recent 200 tweets
# new_tweets = get_tweets(twitter_user, {since_id: latest_tweet_id, count: 200})

# 'twitter' gem documentation:

# Fetch the timeline of Tweets by a user:
# client.user_timeline("gem")
# client.user_timeline(213747670)

# Fetch a user (by screen name or user ID)
# client.user("gem")
# client.user(213747670)

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
    @tweets   =  Tweet.all.order(created_at: :desc)

    # suggest a more descriptive variable name to indicate why you're using the
    # last account specifically
    @account  = Account.last
  end

  def show
    @account = Account.find(params[:id])
  end

  # confusing that this method is the 'update' action when it really creates
  # an account. How does it contrast with teh create action below?
  def update
    @account = Account.create(account_params)

    # this code could be moved into the account model, and you could use an
    # after_create callback (a Rails feature) to ensure it runs anytime
    # an account is created (usually a preferred approach, although this is
    # certainly a fine start).
    new_tweets = TwitterClient.get_tweets(@account.username)
    Tweet.create_with_tweets(new_tweets)
    redirect_to accounts_path
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.create(account_params)
    redirect_to @account
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_path
  end

  def delete_tweets
    @account = Account.find(params[:id])
    @account.tweets.clear
    redirect_to account_url(@account)
  end

  def refresh
    @account = Account.find(params[:id])
    new_tweets = TwitterClient.get_tweets(@account.username)
    Tweet.create_with_tweets(new_tweets)
    redirect_to account_url(@account)
  end

  def deepen
    @account = Account.find(params[:id])
    # I see you following the pattern of using the TwitterClient to get more
    # tweets and then passing the result to the Tweet model... could you just
    # have the twitter client methods handle both steps for you?
    # I'm not 100% suggesting that, it has tradeoffs in terms of re-usability
    # of code, but just posing it as a question...
    new_tweets = TwitterClient.get_more_tweets(@account.username)
    Tweet.create_with_tweets(new_tweets)
    redirect_to account_url(@account)
  end

  # for consitency with the refresh action above, I'd call this refresh_all.
  def update_all
    Account.all.each do |account|
      new_tweets = TwitterClient.get_tweets(account.username)
      Tweet.create_with_tweets(new_tweets)
    end
    redirect_to accounts_path
  end

private
def account_params
    params.require(:account).permit(:username)
end

end



# 'twitter' gem documentation:

# Fetch the timeline of Tweets by a user:
# client.user_timeline("gem")
# client.user_timeline(213747670)

# Fetch a user (by screen name or user ID)
# client.user("gem")
# client.user(213747670)

# def get_account
#   twitter = TwitterClient.new
#   twitter.user(params[:user])
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets   = Tweet.all.order(created_at: :desc)
    @accounts = Account.all
  end


  # you don't have any views for the actions below... I'd suggest removing these
  # actions and the corresponding routes.
  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  # this comment below looks to be out of date... it's important to keep your
  # code and comments clean!
  def create #requires API call, right?
    @tweet = Tweet.create(params[:id])
    redirect_to @tweet
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to accounts_path
  end


  private
  def account_params
      params.require(:account).permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>

  <%= f.label      "Add Account:"     %>
  <%= f.text_field :username, :value => "@..."     %>

  <%= f.submit    "Enter" %>
<% end %>

app/views/accounts/index.html.erb
<h3><%= link_to "New Account", new_account_path %> |
<%= link_to "Load Tweets", update_all_accounts_path %>
<span class="arabiheader">كل المغردات الآخيرة</span></h3>
<div class="container">
  <div class="AccountList">
    <% @accounts.each do |account| %>
    <ul>
      <li>
        <p>
        <%= link_to "@#{account.username}", account_path(account) %> | <%= link_to 'Delete', account_path(account),
                                                                           method: :delete,
                                                                           data: { confirm: 'Are you sure?' } %>
        </p>
      </li>
    </ul>
    <% end %>
      <%= render 'form' %>
  </div>


  <div class="HighlightedTweets">
    <ul class="ArabicTweet">
      <% @account.tweets.each do |tweet| %>
      <li class="ArabicTweetie">
          <%= tweet.text %>
        </p>
        <p class="tweetinfo">
          <%= "tweeted at: #{tweet.created_at} by @#{tweet.account.username}"%>
        </p>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="AllTweets">
    <ul class="ArabicTweet">
      <p>
        <%@tweets.each do |tweet| %>
        <li class="ArabicTweetie">
          <%= tweet.text %>
        </li>
      </p>
      <p class="tweetinfo">
        <%= "tweeted at: #{tweet.created_at} by @#{tweet.account.username}"%>
      </p>
      <% end %>
    </ul>
  </div>
</div>

app/views/accounts/new.html.erb
<%= render 'form' %>

app/views/accounts/show.html.erb
<h2 class="ArabicHeadline">
  <%= "@#{@account.username}" %>
  <%= link_to "refresh", refresh_account_path(@account) %> |
  <%= link_to "more tweets", deepen_account_path(@account) %> |
  <%= link_to "delete account", account_path(@account),
                               method: :delete,
                               data: { confirm: 'Are you sure?' } %> |

  <%= link_to "delete tweets", delete_tweets_account_path(@account),
                               method: :patch,
                               data: { confirm: 'Are you sure?' } %>
</h2>

<div class="AllTweets">
  <ul class="ArabicTweet">
  <% @account.tweets.each do |tweet| %>
  <li class="ArabicTweetie">
    <p class>
      <%= tweet.text %>
    </p>
    <p class="tweetinfo">
      <%= "tweeted at: #{tweet.created_at} by @#{tweet.account.username}"%>
    </p>
  </li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>TwitterScraper</h1>
    <nav>
      <a href="/accounts">Twitter Accounts</a>
      <a href="">Twitter Searches</a>
    </nav>

<%= yield %>

</body>
</html>